const LOGIN_METHOD = {
  PIN: "PIN",
  MASTER_PASSWORD: "MASTER_PASSWORD",
  RECOVERY_PHRASE: "RECOVERY_PHRASE",
  BIOMETRICS: "BIOMETRICS",
} as const;

type LOGIN_METHOD = (typeof LOGIN_METHOD)[keyof typeof LOGIN_METHOD];

export { LOGIN_METHOD };
